const ENDPOINT='http://127.0.0.1:43217';
const ACP=/^acps_[a-z0-9]{8,64}$/i;
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
async function state(patch){await chrome.storage.local.set({status:{...(await chrome.storage.local.get('status')).status,...patch}});}
async function post(route,payload){const {pairingKey}=await chrome.storage.local.get('pairingKey');if(!/^[a-f0-9]{64}$/.test(pairingKey||''))throw new Error('请先在桌面应用中复制配对密钥。');const response=await fetch(ENDPOINT+route,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+pairingKey},body:JSON.stringify(payload),signal:AbortSignal.timeout(5000)});const result=await response.json();if(!response.ok)throw new Error(result.error||`HTTP ${response.status}`);return result;}
async function heartbeatIfPaired(extra={}){const {pairingKey}=await chrome.storage.local.get('pairingKey');if(!/^[a-f0-9]{64}$/.test(pairingKey||''))return false;await post('/v1/heartbeat',{extensionVersion:chrome.runtime.getManifest().version,...extra});await state({lastHeartbeatAt:Date.now(),error:null});return true;}
function validate(p){if(!p||(!ACP.test(p.entityId||'')&&!UUID.test(p.entityId||'')))throw new Error('请输入真实 ACP ID 或 Codex thread ID。');const u=new URL(p.conversationUrl);if(u.protocol!=='https:'||u.hostname!=='chatgpt.com'||!u.pathname.match(/(?:^|\/)c\/[0-9a-f-]{36}$/i))throw new Error('当前页不是 ChatGPT conversation。');const userMessageId=String(p.userMessageId||'').slice(0,120),userMessageText=String(p.userMessageText||'').slice(0,2000);return {entityId:p.entityId,conversationUrl:u.href,title:String(p.title||'').slice(0,250),userMessageId,userMessageText};}
function conversationUrl(raw){const u=new URL(raw);if(u.protocol!=='https:'||u.hostname!=='chatgpt.com'||!u.pathname.match(/(?:^|\/)c\/[0-9a-f-]{36}$/i))throw new Error('当前页不是 ChatGPT conversation。');return u.href;}
function validateRequest(p){if(!p||!['started','completed'].includes(p.phase))throw new Error('请求事件格式不正确。');const userMessageId=String(p.userMessageId||'').slice(0,160);if(!userMessageId)throw new Error('缺少用户消息 ID。');return {conversationUrl:conversationUrl(p.conversationUrl),conversationTitle:String(p.conversationTitle||'').slice(0,250),userMessageId,userMessageText:String(p.userMessageText||'').slice(0,4000),phase:p.phase};}
function validateTool(p){if(!p||!['started','completed'].includes(p.phase)||!/^AgentDock\./i.test(p.toolName||''))throw new Error('工具事件格式不正确。');const invocationId=String(p.invocationId||'').slice(0,160),userMessageId=String(p.userMessageId||'').slice(0,160);if(!invocationId||!userMessageId)throw new Error('工具事件缺少 ID。');return {conversationUrl:conversationUrl(p.conversationUrl),conversationTitle:String(p.conversationTitle||'').slice(0,250),userMessageId,userMessageText:String(p.userMessageText||'').slice(0,4000),invocationId,toolName:String(p.toolName).slice(0,160),action:String(p.action||'').slice(0,80)||null,argsSummary:String(p.argsSummary||'').slice(0,1200)||null,projectHint:String(p.projectHint||'').slice(0,500)||null,entityId:String(p.entityId||'').slice(0,100)||null,taskId:String(p.taskId||'').slice(0,100)||null,phase:p.phase,ok:typeof p.ok==='boolean'?p.ok:null};}
chrome.runtime.onMessage.addListener((message,sender,reply)=>{
  (async()=>{
    const page=sender.url?.startsWith('https://chatgpt.com/');const extension=sender.id===chrome.runtime.id&&sender.url?.startsWith(chrome.runtime.getURL(''));
    if(message.type==='observer-status'&&page){const observer=String(message.kind||'').slice(0,80),observerAt=Date.now();await state({observer,observerAt});await heartbeatIfPaired({pageObserver:observer,pageObserverAt:observerAt});return {ok:true};}
    if(message.type==='bind-observed'&&page){const payload=validate(message.payload);const result=await post('/v1/bind',payload);const current=(await chrome.storage.local.get('status')).status||{};await state({lastBoundAt:Date.now(),lastEntity:payload.entityId,bindingCount:(current.bindingCount||0)+1,error:null});await chrome.action.setBadgeText({text:'✓'});await chrome.action.setBadgeBackgroundColor({color:'#4c8c73'});return result;}
    if(message.type==='request-observed'&&page){const payload=validateRequest(message.payload);const result=await post('/v1/request',payload);await state({lastRequestAt:Date.now(),error:null});return result;}
    if(message.type==='tool-observed'&&page){const payload=validateTool(message.payload);const result=await post('/v1/tool',payload);await state({lastToolAt:Date.now(),lastTool:payload.toolName,error:null});return result;}
    if(message.type==='pair'&&extension){if(!/^[a-f0-9]{64}$/.test(message.key||''))throw new Error('配对密钥格式不正确。');await chrome.storage.local.set({pairingKey:message.key});const result=await post('/v1/heartbeat',{});await state({pairedAt:Date.now(),error:null});return result;}
    if(message.type==='heartbeat'&&extension){const result=await post('/v1/heartbeat',{});await state({error:null});return result;}
    if(message.type==='bind-manual'&&extension){const result=await post('/v1/bind/manual',validate(message.payload));await state({lastBoundAt:Date.now(),error:null});return result;}
    throw new Error('不允许的消息来源。');
  })().then(reply).catch(async error=>{await state({error:String(error.message||error).slice(0,250)});reply({ok:false,error:String(error.message||error)});});
  return true;
});
chrome.runtime.onStartup.addListener(()=>{void heartbeatIfPaired().catch(async error=>{await state({error:String(error.message||error).slice(0,250)});});});
