const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const path=require('node:path');
const p=require('./load-extractor.cjs');const cid='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222';
const user={id:'user-exact',text:'继续'};const context={conversationId:cid,title:'Fixture'};
const invocation=(action='create',recipient='AgentDock.task_manage')=>({id:'invoke-exact',author:{role:'assistant'},recipient,content:{text:JSON.stringify({action,task_id:'tsk_previous',project:'C:\\dev\\fixture'})}});
const result=(name='AgentDock.task_manage')=>({id:'result-exact',author:{role:'tool',name},content:{parts:[JSON.stringify({action:'get',task_id:'tsk_previous',task:{id:'tsk_previous'}})]}});
test('long development turns retain exact ancestry beyond 60 messages',()=>{const mapping={u:{message:{id:user.id,author:{role:'user'},content:{parts:[user.text]}}}};let parent='u';for(let i=0;i<240;i++){mapping['n'+i]={parent,message:{id:'n'+i,author:{role:'assistant'},recipient:'all',channel:'commentary',content:{parts:['working']}}};parent='n'+i;}mapping.call={parent,message:invocation()};mapping.result={parent:'call',message:result()};const view=p.inspectRequestActivities({conversation_id:cid,mapping,current_node:'result'},cid);assert.equal(view.user.id,user.id);assert.equal(view.activities.length,2);assert.equal(view.activities[1].taskId,'tsk_previous');assert.equal(view.final,false);});
test('cyclic current branch cannot fall back to another user by time',()=>{const mapping={a:{parent:'b'},b:{parent:'a'},u:{message:{id:user.id,create_time:20,author:{role:'user'},content:{parts:[user.text]}}}};assert.equal(p.latestUser({mapping,current_node:'a'}),null);});
test('recipient all only completes with an explicit finished end_turn',()=>{const base={author:{role:'assistant'},recipient:'all',content:{parts:['answer']},status:'finished_successfully',end_turn:true};assert.equal(p.isFinal(base),true);assert.equal(p.isFinal({...base,channel:'commentary'}),false);assert.equal(p.isFinal({...base,end_turn:false,channel:'final'}),false);assert.equal(p.isFinal({...base,status:'in_progress'}),false);});
test('reading or lifecycle queries alone never claim another task',()=>{for(const action of ['get','resume','list','complete']){assert.equal(p.invocationActivity(invocation(action),context,user).taskId,'');assert.equal(p.resultActivity(result(),context,invocation(action),user).taskId,'');}});
test('read_file task-shaped output is not a plan ownership claim',()=>{const inv={...invocation(),recipient:'AgentDock.read_file'};assert.equal(p.resultActivity(result('AgentDock.read_file'),context,inv,user).taskId,'');});
test('connector path envelope is recognized without copying command bodies',()=>{const inv={id:'path-call',author:{role:'assistant'},recipient:'api_tool.call_tool',content:{parts:[JSON.stringify({path:'/AgentDock/exec_command',arguments:{workdir:'C:\\dev\\fixture',cmd:'PRIVATE'}})]}};const a=p.invocationActivity(inv,context,user);assert.equal(a.toolName,'AgentDock.exec_command');assert(!a.argsSummary.includes('PRIVATE'));});
test('known conversation envelope uses exact message ids and rejects conflicting tab',()=>{const mapping={u:{message:{id:user.id,author:{role:'user'},content:{text:user.text}}}};const data={conversation:{conversation_id:cid,mapping,current_node:'u'}};assert.equal(p.inspectRequestActivities(data,cid).user.id,user.id);assert.equal(p.inspectRequestActivities(data,other).user,null);});
test('redacted connector call cannot invent task or ACP bindings',()=>{const inv={...invocation(),recipient:'api_tool.call_tool',content:{parts:['The output of this plugin was redacted.']}};assert.equal(p.invocationIdentity(inv),null);assert.equal(p.resultActivity({...result(),author:{role:'tool',name:'api_tool.call_tool'}},context,inv,user),null);});
function background(){const store={},listeners={},requests=[];let offline=true;const event=n=>({addListener:f=>listeners[n]=f});const chrome={runtime:{id:'a'.repeat(32),getURL:s=>'chrome-extension://'+'a'.repeat(32)+'/'+s,getManifest:()=>({version:'0.5.5'}),onMessage:event('message'),onInstalled:event('installed'),onStartup:event('startup')},storage:{local:{get:async keys=>typeof keys==='string'?{[keys]:structuredClone(store[keys])}:Object.fromEntries(keys.map(k=>[k,structuredClone(store[k])])),set:async values=>Object.assign(store,structuredClone(values))}},tabs:{query:async()=>[],onUpdated:event('tab')},scripting:{executeScript:async()=>{}},alarms:{create:()=>{},onAlarm:event('alarm')}};const sandbox={chrome,URL,AbortSignal,setTimeout,clearTimeout,console,fetch:async(url,options)=>{if(offline)throw new Error('offline');requests.push({url,payload:JSON.parse(options.body)});return {ok:true,json:async()=>({ok:true})};}};vm.createContext(sandbox);vm.runInContext(fs.readFileSync(path.join(__dirname,'../extension/background.js'),'utf8'),sandbox);store.pairingKey='a'.repeat(64);return {store,listeners,requests,online:()=>offline=false,send:message=>new Promise(resolve=>listeners.message({...message,observerVersion:'0.5.5'},{id:chrome.runtime.id,url:'https://chatgpt.com/c/'+cid},resolve)),flush:()=>vm.runInContext('flush()',sandbox)};}
test('accepted events survive an offline bridge and retry without losing the request',async()=>{const b=background();const response=await b.send({type:'request-observed',payload:{conversationUrl:'https://chatgpt.com/c/'+cid,userMessageId:user.id,userMessageText:user.text,phase:'started'}});assert.equal(response.ok,true);await new Promise(r=>setTimeout(r,5));assert.equal(b.store.outbox.length,1);b.online();await b.flush();assert.equal(b.store.outbox.length,0);assert.equal(b.requests[0].payload.userMessageId,user.id);assert(!JSON.stringify(b.store.outbox).includes('Bearer'));});
test('concurrent background writes preserve every distinct message id',async()=>{const b=background();await Promise.all(Array.from({length:20},(_,i)=>b.send({type:'request-observed',payload:{conversationUrl:'https://chatgpt.com/c/'+cid,userMessageId:'repeat-'+i,userMessageText:'继续',phase:'started'}})));assert.equal(b.store.outbox.length,20);assert.equal(new Set(b.store.outbox.map(x=>x.payload.userMessageId)).size,20);});

test('real connector link-qualified task_manage path is canonicalized before plan recognition',()=>{const inv={id:'linked-call',author:{role:'assistant'},recipient:'api_tool.call_tool',content:{parts:[JSON.stringify({path:'/AgentDock/link_00000000000000000000000000000000/task_manage',arguments:{action:'create'}})]}};const r=p.resultActivity(result(),context,inv,user);assert.equal(r.toolName,'AgentDock.task_manage');assert.equal(r.taskId,'tsk_previous');assert.equal(p.canonicalToolName('AgentDock.link_0000/exec_command'),'AgentDock.exec_command');assert.equal(p.canonicalToolName('/OtherApp/link_0000/task_manage'),null);});

test('attachment-only user messages retain their exact identity and tool ancestry',()=>{const u={id:'attachment-user',author:{role:'user'},content:{content_type:'multimodal_text',parts:[{content_type:'image_asset_pointer',asset_pointer:'fixture'}]}};assert.deepEqual(p.requestUser({messages:[u]}),{id:'attachment-user',text:'[附件消息]'});const data={conversation_id:cid,current_node:'call',mapping:{u:{message:u},call:{parent:'u',message:invocation()}}};assert.equal(p.inspectRequestActivities(data,cid,u.id).activities.length,1);});
test('hidden editable context is not mistaken for an attachment request',()=>{assert.equal(p.requestUser({messages:[{id:'internal-context',author:{role:'user'},content:{content_type:'user_editable_context'}}]}),null);});

test('checkpoint carries an exact Task reference even when the create result is unavailable',()=>{const inv=invocation('checkpoint');const a=p.invocationActivity(inv,context,user);assert.equal(a.taskId,'tsk_previous');assert.equal(a.action,'checkpoint');assert.equal(p.resultActivity({id:'empty-result',author:{role:'tool',name:'AgentDock.task_manage'},content:{content_type:'code',text:''}},context,inv,user).taskId,'tsk_previous');});
test('code-format structured task results are parsed without scanning stdout',()=>{const r={...result(),content:{content_type:'code',text:JSON.stringify({task_id:'tsk_created',action:'create'})}};assert.equal(p.resultActivity(r,context,invocation(),user).taskId,'tsk_created');});

test('mapping throttling respects Retry-After seconds and dates without immediate fallback reads',()=>{assert.equal(p.retryDelay('150',0),150000);assert.equal(p.retryDelay('Thu, 01 Jan 1970 00:03:00 GMT',0),180000);assert.equal(p.retryDelay(null,0),60000);assert.equal(p.retryDelay('0',0),60000);assert.equal(p.retryDelay('invalid',0),60000);});
