import {useEffect,useState} from 'react';
import {ShieldCheck,Smartphone,Monitor,Download,ExternalLink,LogOut,Wifi,RefreshCw} from 'lucide-react';
import {invoke,APP_VERSION} from './transport';
import type {Snapshot} from './types';
interface InstallPrompt extends Event {prompt:()=>Promise<void>;userChoice:Promise<{outcome:string}>}
interface Setup {version:string;publicUrl:string|null;hostName:string;identity:{kind:string;label:string}}
export function InstallApp(){
 const [prompt,setPrompt]=useState<InstallPrompt|null>(null),[installed,setInstalled]=useState(matchMedia('(display-mode: standalone)').matches),[hint,setHint]=useState(false);
 useEffect(()=>{const onPrompt=(e:Event)=>{e.preventDefault();setPrompt(e as InstallPrompt)};const onInstalled=()=>{setInstalled(true);setPrompt(null)};window.addEventListener('beforeinstallprompt',onPrompt);window.addEventListener('appinstalled',onInstalled);return()=>{window.removeEventListener('beforeinstallprompt',onPrompt);window.removeEventListener('appinstalled',onInstalled)}},[]);
 const install=async()=>{if(!prompt){setHint(true);return;}await prompt.prompt();const choice=await prompt.userChoice;setPrompt(null);if(choice.outcome==='accepted')setInstalled(true);};
 return <section className="panel install-card"><div className="remote-icon"><Smartphone size={26}/></div><div className="eyebrow">YOUR AGENTS, WITH YOU</div><h2>把控制室放进口袋</h2><p>添加到手机主屏幕，直接打开工作总览。手机与电脑网页共用同一份实时数据，不需要复制数据库。</p><button className="primary" onClick={()=>void install()} disabled={installed}><Download size={17}/>{installed?'已在独立应用窗口中使用':'安装 / 添加到主屏幕'}</button>{hint&&<div className="notice"><p>Android：在 Chrome 菜单中选择“添加到主屏幕”或“安装应用”。iPhone：使用 Safari 的“分享 → 添加到主屏幕”。这是一款可安装的 PWA，不是独立 APK。</p></div>}<small>不缓存聊天、命令或监控快照。离线时会明确提示；当前没有后台推送通知。</small></section>
}
export function RemoteSettings({snapshot,notify}:{snapshot:Snapshot;notify:(s:string)=>void}){
 const [setup,setSetup]=useState<Setup|null>(null);
 useEffect(()=>{invoke<Setup>('get_setup_info').then(setSetup).catch(e=>notify(String(e)))},[]);
 const diagnostics=()=>{const value={version:APP_VERSION,generatedAt:snapshot.generatedAt,stale:snapshot.stale,collectionMs:snapshot.collectionMs,stats:snapshot.stats,sourceHealth:Object.fromEntries(Object.entries(snapshot.sources||{}).map(([k,v])=>[k,v.healthy]))};const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='agent-monitor-diagnostics.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 return <div className="settings-grid remote-settings"><InstallApp/><section className="panel"><div className="section-heading"><h2><Monitor size={18}/> 家里的电脑</h2><span className="proof-badge"><ShieldCheck size={14}/>{setup?.identity.kind==='cloudflare-access'?'Cloudflare Access':'本机访问'}</span></div><dl className="facts ids"><div className="field"><dt>采集主机</dt><dd>{setup?.hostName||'正在读取'}</dd></div><div className="field"><dt>当前登录</dt><dd>{setup?.identity.label||'正在确认'}</dd></div><div className="field"><dt>远程地址</dt><dd>{setup?.publicUrl||location.origin}</dd></div><div className="field"><dt>最近快照</dt><dd>{snapshot.generatedAt?new Date(snapshot.generatedAt).toLocaleString():'尚未收到'}</dd></div><div className="field"><dt>版本</dt><dd>{setup?.version||APP_VERSION}</dd></div></dl><div className="remote-actions"><button className="secondary" onClick={()=>location.reload()}><RefreshCw size={16}/>重新连接</button>{setup?.identity.kind==='cloudflare-access'&&<a className="secondary" href="/cdn-cgi/access/logout"><LogOut size={16}/>退出登录</a>}</div></section><section className="panel"><h3><Wifi size={17}/> 真实数据源</h3>{[['acp','AgentDock ACP'],['codex','Codex threads'],['history','Turn / tools'],['locks','进程归属'],['agentdock','AgentDock 服务']].map(([id,label])=><div className="source-row" key={id}><strong>{label}</strong><span className={`source-dot ${snapshot.sources?.[id]?.healthy?'good':'bad'}`}>{snapshot.sources?.[id]?.healthy?'已连接':'不可用 / 未知'}</span></div>)}</section><section className="panel"><h3>网页版可以做什么</h3><p className="muted">查看工作、模型、token、工具与时间线；搜索和筛选；明确绑定或移除对话来源；关联 AgentDock 任务。绑定修改会同步到 Windows 桌面版。</p><div className="notice"><ShieldCheck size={18}/><p>不提供远程 shell、终止 / 重启 Agent、任意文件读取或系统设置修改。浏览器扩展配对密钥只能在家里电脑的桌面版查看。</p></div><button className="secondary" onClick={diagnostics}><Download size={15}/>导出不含私密内容的诊断信息</button></section></div>
}
