export interface Event { id:string; kind:string; name:string; status:string; startMs:number; endMs:number|null; durationMs:number|null; command:string|null; file:string|null; tokenDelta:number|null; turnId:string|null; toolSessionId:string|null; source:string; }
export interface Turn { id:string; status:string; startMs:number; endMs:number|null; durationMs:number|null; error:string|null; source:string; }
export interface Binding { entityId:string; conversationId:string; title:string; url:string; source:string; observedAt:number; inheritedFromThread?:string; }
export interface Acp { id:string; remoteSessionId:string; parentId:string; cwd:string; agent:string; modeId:string; status:string; stopReason:string|null; createdAt:number|null; updatedAt:number|null; closedAt:number|null; }
export interface Process {pid:number;parentPid:number|null;name:string;exe:string|null;role:string;cpu:number|null;memory:number;startedAt:number;status:string;}
export interface Task {id:string;title:string;goal:string;project:string;status:string;phase:string;steps:{id:string;title:string;status:string}[];updatedAt:number;createdAt:number;completedAt:number|null;}
export interface MonitorTask {id:string;conversationId:string;title:string;goal:string;project:string;projects?:string[];status:string;origin:string;sourceMessageId:string;createdAt:number;updatedAt:number;completedAt:number|null;agentIds:string[];members:{entityId:string;userMessageId:string;linkedAt:number}[];}
export interface RequestTool {invocationId:string;toolName:string;action:string|null;argsSummary:string|null;projectHint:string|null;entityId:string|null;taskId:string|null;status:string;startedAt:number;finishedAt:number|null;ok:boolean|null;}
export interface ChatRequest {id:string;conversationId:string;userMessageId:string;conversationTitle:string;prompt:string;startedAt:number;completedAt:number|null;updatedAt:number;lastActivityMs:number;agentdockTaskId:string|null;projectHint:string|null;project:string;status:string;progressProtocol:'not-needed'|'claimed'|'unclaimed';progress?:{completed:number;total:number;currentStep:string|null;revisionCount?:number};plan?:Task;plans?:Task[];tools:RequestTool[];agentIds:string[];}
export interface Agent { id:string;title:string;source:string;project:string;cwd:string;acpSessions:Acp[];parentThreadId:string|null;childThreadIds:string[];binding:Binding|null;attributionConflict:boolean;archived?:boolean;archivedAt?:number|null;model:string|null;threadModel:string|null;modelProvider:string|null;reasoningEffort:string|null;tokensUsed:number|null;tokenSource:string;modelSource:string;status:string;statusEvidence:string[];statusConfidence:string;turn:Turn|null;currentTool:Event|null;lastTool:Event|null;lastCommand:string|null;lastFile:string|null;lastActivityMs:number;createdAt:number;updatedAt:number;hostPid:number|null;hostPids:number[];hostProcess:Process|null;childProcesses:Process[];processAttribution:string;task:Task|null;taskAssociation:string;rolloutPartial:boolean;rolloutCatchingUp:boolean;sourceWarning:string|null;agentRole:string|null;agentNickname:string|null;}
export interface SourceHealth {healthy?:boolean;path?:string;error?:string|null;threadCount?:number;loadedThreads?:number;count?:number;port?:number;mappedThreads?:number;lastExtensionSeen?:number|null;lastBindingAt?:number|null;extensionOrigin?:string|null;extensionVersion?:string|null;pageObserver?:string|null;lastPageObserverSeen?:number|null;projectedThreadCount?:number;readOnly?:boolean;errors?:string[];itemReadErrors?:number;thresholdHours?:number;lastSweepAt?:number|null;closedSessions?:number;expiredLocalThreads?:number;failed?:number;pendingBatch?:number;activeVersion?:string|null;indexedSkill?:string;}
export interface Analytics {days:number;startMs:number;observedTokens:number;firstObservedAt:number|null;byModel:{name:string;tokens:number}[];byProject:{name:string;tokens:number}[];byThread:{name:string;tokens:number}[];completedTurns:number;failedTurns:number;coverage:string;}
export interface Snapshot { lastAttemptAt?:number; version?:string;generatedAt?:number;collectionMs?:number;loading?:boolean;stale:boolean;collectorError?:string;agents:Agent[];processes:Process[];tasks:Task[];monitorTasks?:MonitorTask[];requests?:ChatRequest[];bindings:Binding[];stats?:{active:number;waiting:number;stalled:number;failed:number;completed:number;observedTokensToday:number;unassignedAcp:number};analyticsToday?:Analytics;sources?:Record<string,SourceHealth>;settings?:{dataDir:string;codexHome:string;agentdockHome:string;refreshMs:number};coverage?:string;}
export interface Detail {events:Event[];projectionAvailable?:boolean;partial:boolean;notice:string;warning?:string;}
